[package]
name = "mandlebrot"
version = "0.1.0"
authors = ["Randy Horman <rwhorman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.0"
image = "0.23.6"
crossbeam = "0.8.1"
